### ISSUE TITLE
Does it support ACME Protocol v2?

### ISSUE THREAD

**Issue by humayunghani** [acmephp/documentation#19]
Hey,

Do you have any plans to upgrade library to support ACME v2 protocol? I've using this library and LE is going to stop supporting v1 client requests from 1st June, 2020. I'm not sure what to do now.
Can you or anybody suggest me any other good ACME php client?

Thanks.

**Comment by tgalopin** [comment]
Hello!

Yes it does :) it should be already using it transparently, do you have any issue with it?

**Comment by humayunghani** [comment]
Yes, I'm getting emails from LE stating that I'm using ACMEv1 protocol in the past two weeks to register certificates. Further they state this...

```
According to our records, the software client you're using to get Let's
Encrypt TLS/SSL certificates issued or renewed at least one HTTPS certificate
in the past two weeks using the ACMEv1 protocol. Here are the details of one
recent ACMEv1 request from each of your account(s):

Client IP address:  xxx.xxx.xxx.xxx
```

```
Beginning June 1, 2020, we will stop allowing new domains to validate using
the ACMEv1 protocol. You should upgrade to an ACMEv2 compatible client before
then, or certificate issuance will fail. For most people, simply upgrading to
the latest version of your existing client will suffice. You can view the
client list at: https://letsencrypt.org/docs/client-options/
```

I'm only using your client library to register certificates. Am I missing something here? Is there a way to upgrade your library to latest version to be able to use ACMEv2 protocol?

Here is the snippet from my composer.json...

```
"require": {
        "php": ">=5.6.4",
        "acmephp/acmephp": "1.0.x-dev",
        "beberlei/assert": "^2.7",
        "guzzlehttp/guzzle": "^6.2",
        "laravel/framework": "5.4.*",
        "laravel/tinker": "~1.0"
    },
```

Thanks.

**Comment by tgalopin** [comment]
Ah, you're using the library directly? Could you tell me which version you are currently using (using composer show for instance)?

**Comment by humayunghani** [comment]
Yes I'm using your core library in my Certificate Service API.
Here's the result of my composer show...

```
name     : acmephp/acmephp
descrip. : Let's Encrypt client written in PHP
keywords : ACME, acmephp, certificate, cli, csr, encryption, https, letsencrypt, openssl, ssl, x509
versions : * dev-master, 1.0.x-dev
type     : project
license  : MIT License (MIT) (OSI approved) https://spdx.org/licenses/MIT.html#licenseText
homepage : https://github.com/acmephp/acmephp
source   : [git] https://github.com/acmephp/acmephp.git 0b4ea8b586e028ba4ea7f7411adfd2ec7b77c095
dist     : [zip] https://api.github.com/repos/acmephp/acmephp/zipball/0b4ea8b586e028ba4ea7f7411adfd2ec7b77c095 0b4ea8b586e028ba4ea7f7411adfd2ec7b77c095
path     : /home/forge/certservice.secure.website/vendor/acmephp/acmephp
names    : acmephp/acmephp

autoload
psr-4
AcmePhp\ => src/

requires
ext-openssl *
guzzlehttp/guzzle ^6.0
league/flysystem ^1.0.19
league/flysystem-sftp ^1.0.7
monolog/monolog ^1.19
padraic/phar-updater ^1.0
php >=5.5.0
swiftmailer/swiftmailer ^5.4
symfony/config ^3.0
symfony/console ^3.0
symfony/dependency-injection ^3.0
symfony/serializer ^3.0
symfony/yaml ^3.0
webmozart/assert ^1.0
webmozart/path-util ^2.3

requires (dev)
league/flysystem-memory ^1.0
phpunit/phpunit ^4.8.31|^5.7.3
sllh/php-cs-fixer-styleci-bridge ^1.5.0
symfony/finder ^3.0
symfony/phpunit-bridge ^3.1
symfony/process ^3.0
```

**Comment by tgalopin** [comment]
My bad, it's `composer info` to see the actual precise version installed :)

**Comment by humayunghani** [comment]
acmephp/acmephp                       dev-master 0b4ea8b Let's Encrypt client written in PHP

**Comment by tgalopin** [comment]
Ah, this is why :) . You are currently using a version released in January 2017: https://github.com/acmephp/acmephp/commit/0b4ea8b. You should update the library to the latest version. Also, I recommend you to use a stable rlease (something like `^1.2`) to avoid problems.

**Comment by humayunghani** [comment]
Oh ok thanks. So should I just change the version to ^1.2 in my composer.json and update it? Could this possibly break something or is this version compatible? I'm using it on production.

**Comment by tgalopin** [comment]
Yes, you should be able to update to upgrade to 1.2 by updating your composer.json file.

You may indeed need to update a bit your application as you were using a dev build released during the beta, meaning that there was quite a lot of work since then. Have a try in local :) .

**Comment by humayunghani** [comment]
Ok Thanks bro. Where can I find your lastest core library's reference documentation?

**Comment by tgalopin** [comment]
There is not much documentation about the core library itself yet. However, if you already have a working implementation, it should be quite straight forward :) .

**Comment by humayunghani** [comment]
Ok yeah I'll look into the code then. Thanks a lot.
